{% set python_min = '3.10' %}
{% set name = "txl-local-terminals" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_local_terminals-{{ version }}.tar.gz
  sha256: bf9ea9e029caeef2c2cef01be6fdadf75ea161726d5abe86137849ea4da72bef

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - __unix  # [unix]
    - __win  # [win]
    - pywinpty  # [win]
    - anyio >=3.7.0,<5

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_local_terminals

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_terminals
  summary: TXL plugin for local terminals
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_terminals
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
